### ISSUE TITLE
Client crash seemingly from having them lay and get up too many times (1.12.2 version, Tekkit 2 modpack)

### ISSUE THREAD

**Issue by SmolFloofyRedhead** [iChun/LetSleepingDogsLie#10]
I was trying to get the right pose for a puppy to sploot. I never got the sploot. When I logged off the server I was on, I got a client crash, and it also caused the VanillaFix-like mod that Tekkit 2 has to loop, forcing me to close the game.
I've attached one of the several crash reports, as each time I tried to continue, it made a new one.
At first, I thought it was because I had a chunk loader, so I disabled it. That made no difference, cause after having them all stand up and sit back down, the crashes stopped with or without chunkloading.
[](url)
[crash-2022-09-04_00.03.56-client.txt](https://github.com/iChun/LetSleepingDogsLie/files/9484214/crash-2022-09-04_00.03.56-client.txt)

**Comment by iChun** [comment]
Not a LSDL crash, some other mod is spawning a player and not defining a player info for it and it's causing an NPE and crashing. LSDL just happens to be the mod inciting the crash, I'm afraid.

Now the problem is figuring out which mod is actually doing that...
