### ISSUE TITLE
Compatibility with the mod "revamped wolf"

### ISSUE THREAD

**Issue by Blugori** [iChun/LetSleepingDogsLie#5]
Hi , I love using your mod but I encountered an incompatibility with the mod "revamped wolf". This mod adds armors models for wolfs but the armor stay in "sit position" when the dog lie.
I was wondering if you could fix it or if the creator of revamped wolf should do it

thanks for your work :)

**Comment by Girzm** [comment]
never fixed still,

**Comment by iChun** [comment]
> never fixed still,

You're welcome to add compatibility for the mod if you'd like via a pull request, then I can mark this issue as closed :)
