### ISSUE TITLE
Permission to upload Fabric port

### ISSUE THREAD

**Issue by IMS212** [iChun/LetSleepingDogsLie#6]
Couldn't find any other way to contact you, so here I am. I've made a complete Fabric port of the mod at https://github.com/IMS212/LetSleepingDogsLie-Fabric and was wondering if I could publish it as an unofficial version?

**Comment by iChun** [comment]
By all means, go ahead. 

I did have plans for a Fabric version, but time constraints due to IRL have gotten in the way, so it'll be a bit before I do do it.

As long as you comply to the project's license (tldrlegal.com can help with this), and give credit where due, there should be no issues.

**Comment by IMS212** [comment]
Thanks! I’ve published it on curseforge and modrinth under “Let Sleeping Dogs Lie - Fabric (Unofficial)”, and am waiting for it to be approved.
