### ISSUE TITLE
Optifine renders collars weird

### ISSUE THREAD

**Issue by Gixelman** [iChun/LetSleepingDogsLie#8]
If you use Optfine the Collars of the Wolves render weird and when they lie down they flie above their heads.
I checked the settings, nothing changes it. Pls Fix

**Comment by philipt4** [comment]
After looking into this further the issue does seem to be isolated to Optifine uses.
Have you looked into this @iChun

**Comment by iChun** [comment]
No I have not, and it is unlikely I'll be able to anytime soon.

Might be worth adding screenshots for reference btw.

Worth mentioning that I usually do not provide support for issues with mods
which can be directly attributed to Optifine as they have a reputation of
causing issues with forge mods and the onus is usually on them to maintain
compatibility with Forge mods.

**Comment by philipt4** [comment]
![image](https://user-images.githubusercontent.com/35475073/196512611-6dbbcc29-34e4-497e-b7be-942c707eaad4.png)
@iChun Screenshot of described issue here

**Comment by iChun** [comment]
Thanks. It looks like the collar model is still in the sitting pose. I'm
looking at the code now and I'm surprised this doesn't also happen in
vanilla.

I don't know when I'll be able to look into addressing this but when I have
there'll be an update to this issue.

**Comment by iChun** [comment]
Unlikely to be an issue anymore due to my changes to the code for the 1.19.3 update. Will mark as fixed, please let me know if the update (when it's out) hasn't fixed hte issue.
