### ISSUE TITLE
[1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [iChun/LetSleepingDogsLie#9]
Forge 41.0.94+
LetSleepingDogsLie-1.19-1.1.1

The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Let Sleeping Dogs Lie (dogslie) encountered an error during the done event phase

[crashlog](https://github.com/iChun/LetSleepingDogsLie/files/9126997/crash-2022-07-17_13.34.27-client.txt)

**Comment by iChun** [comment]
Already fixed and updated
